name: Charmhub Upload
description: Uploads a charm to charmhub.io
author: Kenneth Koski
inputs:
  destructive-mode:
    required: false
    default: true
    description: |
      Can be used to turn off destructive mode while building.
      This might be useful when building for other architectures than the one
      of the runner.
  channel:
    required: false
    default: latest/edge
    description: |
      Channel to publish the charm in
  tag-prefix:
    required: false
    description: |
      Tag prefix, useful when bundling multiple charms in the same repo using a matrix.
  charm-path:
    required: false
    default: '.'
    description: |
      Path to charm directory
  built-charm-path:
    required: false
    description: |
      Path to a pre-built charm.
  charmcraft-channel:
    required: false
    default: 'latest/stable'
    description: |
      Snap channel to use when installing charmcraft
  upload-image:
    required: false
    default: 'true'
    description: |
      Set to false if you don't want to update the OCI image
  pull-image:
    required: false
    default: 'true'
    description: |
      Set to false if you want to skip pulling OCI images. If false,
      the OCI images must be present in the local docker registry prior
      to running the action. Set the upstream-source key in metadata.yaml
      to the name of the local image.
  credentials:
    required: true
    description: |
      Credentials exported from `charmcraft login --export`. See
      https://juju.is/docs/sdk/remote-env-auth for more info
  github-token:
    required: true
    description: |
      Github Token needed for automatic tagging when publishing
  resource-overrides:
    required: false
    default: ""
    description: |
      Assign static charm resource revisions. If omitted, the latest
      revision will be used. Separate entries using commas.
      
      Example: "promql-transform:2,prometheus-image:12"   
runs:
  using: node16
  main: ../dist/upload-charm/index.js
branding:
  icon: upload-cloud
  color: orange
