name: Test Charmhub Upload

on:
  push:
    branches:
      - 'track/*'
      - 'main'
  pull_request:
    branches:
      - 'track/*'
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Execute tests
        run: |
          npm run test
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run format
          npm run lint
