name: Test Charmhub Upload

on:
  push:
    branches:
      - 'track/*'
      - 'main'
  pull_request:
    branches:
      - 'track/*'
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Execute tests
        run: |
          npm run test
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run format
          npm run lint
