name: GitHub Actions Demo

on: [push]

jobs:
  ensure-compiled:
    runs-on: ubuntu-latest
    name: Ensure ncc compilation
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: ./hooks/pre-commit

  upload_to_charmhub:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Upload to charmhub
        uses: ./
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          upload-image: true
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: my-logs
    #     path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/ # or path/to/artifact
